export const TRANSACTION_TYPE = { 
  FUNCTION_CALL: 'FUNCTION_CALL',
  TRANSFER: 'TRANSFER',
  ADD_KEY: 'ADD_KEY',
  DELETE_KEY: 'DELETE_KEY',
  DEPLOY_CONTRACT: 'DEPLOY_CONTRACT',
  STAKE: 'STAKE',
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT'
};

export const TRANSACTION_SUB_TYPE = { 
  SEND: 'SEND',
  RECEIVE: 'RECEIVE',
  TRANSFER_TO_AURORA: 'TRANSFER_TO_AURORA'
};